---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: deps
    image: golang:1.20
    commands:
      - make deps
    volumes:
      - name: godeps
        path: /go

  - name: lint
    image: golang:1.20
    commands:
      - make lint
    volumes:
      - name: godeps
        path: /go

  - name: test
    image: golang:1.20
    commands:
      - make test
    volumes:
      - name: godeps
        path: /go

volumes:
  - name: godeps
    temp: {}

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
  - name: changelog-generate
    image: thegeeklab/git-chglog
    commands:
      - git fetch -tq
      - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased unreleased}

  - name: changelog-format
    image: thegeeklab/alpine-tools
    commands:
      - prettier CHANGELOG.md
      - prettier -w CHANGELOG.md

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      note: CHANGELOG.md
      overwrite: true
      title: ${DRONE_TAG}
    when:
      ref:
        - refs/tags/**

image_pull_secrets:
  - docker_config

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - test

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

steps:
  - name: markdownlint
    image: thegeeklab/markdownlint-cli
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  - name: spellcheck
    image: thegeeklab/alpine-tools
    commands:
      - spellchecker --files 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article syntax-urls --no-suggestions
    environment:
      FORCE_COLOR: true
      NPM_CONFIG_LOGLEVEL: error

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - release

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: matrix
    image: thegeeklab/drone-matrix
    settings:
      homeserver:
        from_secret: matrix_homeserver
      password:
        from_secret: matrix_password
      roomid:
        from_secret: matrix_roomid
      template: "Status: **{{ .Build.Status }}**<br/> Build: [{{ .Repo.Owner }}/{{ .Repo.Name }}]({{ .Build.Link }}){{ if .Build.Branch }} ({{ .Build.Branch }}){{ end }} by {{ .Commit.Author }}<br/> Message: {{ .Commit.Message.Title }}"
      username:
        from_secret: matrix_username
    when:
      status:
        - success
        - failure

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
  status:
    - success
    - failure

depends_on:
  - docs

---
kind: signature
hmac: 1821966cd39f3db56d3ac90e1c75f488b9eb09644791399a2a259a008d8a2985

...
